### ISSUE TITLE
0.113 changes

### ISSUE THREAD

**Issue by sagitt** [home-assistant-community-themes/midnight#22] opened 2020-07-26 20:47 UTC
not work very well on 0.113

card bordes.
![Schermata 2020-07-26 alle 22 47 05](https://user-images.githubusercontent.com/169086/88489027-f1abd800-cf91-11ea-8db7-2f2c1644a8ac.png)

**Comment by pho3nixf1re** [comment] 2020-07-26 20:59
Please see fix in #21 . I am waiting on approval form @maartenpaauw to merge as I do not have the ability to override that requirement.

**Comment by pho3nixf1re** [comment] 2020-07-26 21:00
Duplicate of #18

**Closed as completed by pho3nixf1re** 2020-07-26 21:00 UTC

**Comment by pho3nixf1re** [comment] 2020-07-28 14:45
The fix has been merged. Once you update this should be resolved.
